"""Type stubs for the fast_qr Rust extension module."""

class ECL:
    L: ECL
    M: ECL
    Q: ECL
    H: ECL
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

class Mode:
    Numeric: Mode
    Alphanumeric: Mode
    Byte: Mode
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

class Version:
    def __new__(cls, v: int) -> Version: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

class Mask:
    Checkerboard: Mask
    HorizontalLines: Mask
    VerticalLines: Mask
    DiagonalLines: Mask
    LargeCheckerboard: Mask
    Fields: Mask
    Diamonds: Mask
    Meadow: Mask
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

class Shape:
    Square: Shape
    Circle: Shape
    RoundedSquare: Shape
    Vertical: Shape
    Horizontal: Shape
    Diamond: Shape
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

class ImageBackgroundShape:
    Square: ImageBackgroundShape
    Circle: ImageBackgroundShape
    RoundedSquare: ImageBackgroundShape
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...

class Color:
    def __new__(cls, color: str | list[int]) -> Color: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

class QRCode:
    @property
    def size(self) -> int: ...
    @property
    def matrix(self) -> list[list[bool]]: ...
    def to_str(self) -> str: ...
    def __repr__(self) -> str: ...

class QRBuilder:
    def __new__(cls, data: str | bytes) -> QRBuilder: ...
    def ecl(self, ecl: ECL) -> QRBuilder: ...
    def mode(self, mode: Mode) -> QRBuilder: ...
    def version(self, version: Version) -> QRBuilder: ...
    def mask(self, mask: Mask) -> QRBuilder: ...
    def build(self) -> QRCode: ...

class SvgBuilder:
    def __new__(cls) -> SvgBuilder: ...
    def margin(self, margin: int) -> SvgBuilder: ...
    def module_color(self, color: Color) -> SvgBuilder: ...
    def background_color(self, color: Color) -> SvgBuilder: ...
    def shape(self, shape: Shape) -> SvgBuilder: ...
    def shape_color(self, shape: Shape, color: Color) -> SvgBuilder: ...
    def image(self, image: str) -> SvgBuilder: ...
    def image_background_color(self, color: Color) -> SvgBuilder: ...
    def image_background_shape(self, shape: ImageBackgroundShape) -> SvgBuilder: ...
    def image_size(self, size: float) -> SvgBuilder: ...
    def image_gap(self, gap: float) -> SvgBuilder: ...
    def image_position(self, x: float, y: float) -> SvgBuilder: ...
    def to_str(self, qr: QRCode) -> str: ...
    def to_file(self, qr: QRCode, path: str) -> None: ...

class ImageBuilder:
    def __new__(cls) -> ImageBuilder: ...
    def fit_width(self, width: int) -> ImageBuilder: ...
    def fit_height(self, height: int) -> ImageBuilder: ...
    def margin(self, margin: int) -> ImageBuilder: ...
    def module_color(self, color: Color) -> ImageBuilder: ...
    def background_color(self, color: Color) -> ImageBuilder: ...
    def shape(self, shape: Shape) -> ImageBuilder: ...
    def shape_color(self, shape: Shape, color: Color) -> ImageBuilder: ...
    def image(self, image: str) -> ImageBuilder: ...
    def image_background_color(self, color: Color) -> ImageBuilder: ...
    def image_background_shape(self, shape: ImageBackgroundShape) -> ImageBuilder: ...
    def image_size(self, size: float) -> ImageBuilder: ...
    def image_gap(self, gap: float) -> ImageBuilder: ...
    def image_position(self, x: float, y: float) -> ImageBuilder: ...
    def to_bytes(self, qr: QRCode) -> bytes: ...
    def to_file(self, qr: QRCode, path: str) -> None: ...
